# Generated by Django 4.1.7 on 2023-03-30 11:52

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0002_rename_vehicle_id_user_data_device_id_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user_data',
            new_name='Vechicle_details',
        ),
    ]
