# Generated by Django 4.1.7 on 2023-03-30 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_user_data_vechicle_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vechicle_details',
            name='device_id',
            field=models.CharField(max_length=65, unique=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='vechicle_details',
            name='vehicle_name',
            field=models.CharField(max_length=500, unique=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='vechicle_details',
            name='vehicle_number',
            field=models.CharField(max_length=65, unique=True, verbose_name=''),
        ),
    ]
