# Generated by Django 4.1.7 on 2023-03-30 17:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0004_alter_vechicle_details_device_id_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vechicle_details',
            new_name='Vehicle_details',
        ),
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_data_1', models.FloatField()),
                ('sensor_data_2', models.FloatField()),
                ('sensor_data_3', models.FloatField()),
                ('sensor_data_4', models.FloatField()),
                ('sensor_data_5', models.FloatField()),
                ('sensor_data_6', models.FloatField()),
                ('sensor_data_7', models.FloatField()),
                ('sensor_data_8', models.FloatField()),
                ('sensor_data_9', models.FloatField()),
                ('sensor_data_10', models.FloatField()),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.vehicle_details')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
