# Generated by Django 4.1.7 on 2023-03-30 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_rename_vechicle_details_vehicle_details_sensordata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensordata',
            name='user',
        ),
    ]
