# Generated by Django 4.1.7 on 2023-03-31 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_sensordata_time_vehicle_details_last_login_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle_details',
            name='user_email',
        ),
    ]
