# Generated by Django 4.1.7 on 2023-03-31 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_rename_vehicle_details_deviced'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensordata',
            name='sensor_data_1',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='sensor_data_10',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='sensor_data_2',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='sensor_data_3',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='sensor_data_4',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='sensor_data_5',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='sensor_data_6',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='sensor_data_7',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='sensor_data_8',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='sensor_data_9',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='time',
            field=models.DateTimeField(null=True),
        ),
    ]
