# Generated by Django 4.1.7 on 2023-03-31 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_sensordata_sensor_data_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deviced',
            name='last_login_time',
        ),
    ]
