# Generated by Django 4.1.7 on 2023-04-05 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_remove_deviced_last_login_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviced',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
    ]
