# Generated by Django 4.1.7 on 2023-04-07 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_deviced_is_online'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deviced',
            name='vehicle_name',
        ),
        migrations.AddField(
            model_name='deviced',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deviced',
            name='long',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
