# Generated by Django 4.1.7 on 2023-04-09 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_remove_deviced_vehicle_name_deviced_lat_deviced_long'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensordata',
            old_name='sensor_data_1',
            new_name='gaslink',
        ),
        migrations.RenameField(
            model_name='sensordata',
            old_name='sensor_data_2',
            new_name='humidity',
        ),
        migrations.RenameField(
            model_name='sensordata',
            old_name='sensor_data_3',
            new_name='temperaturea',
        ),
        migrations.RenameField(
            model_name='sensordata',
            old_name='sensor_data_4',
            new_name='temperatured',
        ),
        migrations.RenameField(
            model_name='sensordata',
            old_name='sensor_data_5',
            new_name='vibration',
        ),
        migrations.RenameField(
            model_name='sensordata',
            old_name='sensor_data_6',
            new_name='voltage',
        ),
    ]
