# Generated by Django 4.1.7 on 2023-04-10 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_rename_sensor_data_1_sensordata_gaslink_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviced',
            name='vehicle_name',
            field=models.CharField(default='demov', max_length=65, verbose_name=''),
            preserve_default=False,
        ),
    ]
