# Generated by Django 4.1.7 on 2023-04-10 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_deviced_vehicle_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensordata',
            old_name='sensor_data_7',
            new_name='fangle',
        ),
    ]
