# Generated by Django 4.1.7 on 2023-04-11 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_rename_sensor_data_7_sensordata_fangle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensordata',
            old_name='time',
            new_name='timed',
        ),
    ]
